#!/bin/bash
# CloudCost Guardian - Interactive Setup Script
# No editor required!

set -e

echo "═══════════════════════════════════════════════"
echo "  CloudCost Guardian - Quick Setup"
echo "═══════════════════════════════════════════════"
echo ""

# Check prerequisites
echo "✓ Checking prerequisites..."

if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not found. Install from: https://www.terraform.io/downloads"
    exit 1
fi

if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Install from: https://aws.amazon.com/cli/"
    exit 1
fi

if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Run: aws configure"
    exit 1
fi

echo "✓ All prerequisites met!"
echo ""

# Install Python dependencies
echo "📦 Installing Python dependencies..."
pip install -q -r requirements.txt
echo "✓ Dependencies installed"
echo ""

# Collect configuration
echo "⚙️  Configuration"
echo "────────────────────────────────────────────────"

read -p "Enter your email for cost alerts: " alert_email

while [[ ! "$alert_email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
    echo "❌ Invalid email format"
    read -p "Enter your email for cost alerts: " alert_email
done

read -p "AWS Region [us-east-1]: " aws_region
aws_region=${aws_region:-us-east-1}

read -p "Environment [dev]: " environment
environment=${environment:-dev}

read -p "Daily cost threshold for alerts [$100]: " threshold
threshold=${threshold:-100}

echo ""
echo "✓ Configuration collected"
echo ""

# Create terraform.tfvars
echo "📝 Creating Terraform configuration..."
cd terraform

cat > terraform.tfvars <<EOF
# CloudCost Guardian Configuration
# Generated by setup script on $(date)

# AWS Configuration
aws_region  = "$aws_region"
environment = "$environment"

# Alert Configuration
alert_email            = "$alert_email"
cost_threshold_percent = $threshold

# Schedule (daily at 8 AM UTC)
analysis_schedule = "cron(0 8 * * ? *)"
EOF

echo "✓ Configuration file created"
echo ""

# Initialize Terraform
echo "🔧 Initializing Terraform..."
terraform init -upgrade
echo ""

# Show plan
echo "📋 Terraform will create the following resources:"
echo "────────────────────────────────────────────────"
terraform plan -compact-warnings | grep -E "^\s+(#|\+|~|-)" | head -20
echo "   ... (run 'terraform plan' to see full details)"
echo ""

# Confirm deployment
read -p "🚀 Deploy CloudCost Guardian? (yes/no): " confirm

if [[ "$confirm" != "yes" ]]; then
    echo "❌ Deployment cancelled"
    exit 0
fi

echo ""
echo "🚀 Deploying infrastructure..."
terraform apply -auto-approve

echo ""
echo "═══════════════════════════════════════════════"
echo "  ✅ CloudCost Guardian Deployed Successfully!"
echo "═══════════════════════════════════════════════"
echo ""
echo "📧 IMPORTANT: Check your email ($alert_email)"
echo "   You'll receive an SNS subscription confirmation."
echo "   Click the link to activate cost alerts."
echo ""
echo "📊 Next Steps:"
echo "   • Wait 24 hours for first cost analysis"
echo "   • View data in AWS Console → DynamoDB"
echo "   • Check CloudWatch Logs for Lambda execution"
echo ""
echo "🔧 Management Commands:"
echo "   • View logs:    aws logs tail /aws/lambda/cloudcost-guardian-$environment-cost-analyzer --follow"
echo "   • Test Lambda:  aws lambda invoke --function-name cloudcost-guardian-$environment-cost-analyzer output.json"
echo "   • Destroy:      cd terraform && terraform destroy"
echo ""
